### ISSUE TITLE
close sidebar on link click

### ISSUE THREAD

**Issue by thekingofjibs** [ystv/my-tv#18]

**Comment by thekingofjibs** [comment]
Haven't figured out how to pass everything about yet. For now, handleDrawerCloseOnLink is commented out in DrawerLinkComponents, maybe there's a better way to close the drawer?

**Comment by rmil** [comment]
Could you add a onClick prop to your buttons which you could then use to trigger the visibility state to update? Although I haven't had a nosey at the code yet

**Comment by thekingofjibs** [comment]
You're probably right, I just need to look at it in the better context once it's cleaned up a bit - I started making the menu tidier but there's still some work to be done
