### ISSUE TITLE
Docker build process

### ISSUE THREAD

**Issue by thekingofjibs** [ystv/my-tv#3]

**Comment by thekingofjibs** [comment]
Docker and Jenkins integraeted

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by thekingofjibs** [comment]
Docker and Jenkins integrated

**Comment by rmil** [comment]
Docker and Jenkins integrated
